name: reluna_family
description: Reluna Family Governance - Family management and decision-making app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.17.6              # SHADCN UI LIBRARY (compatible with Flutter 3.27)
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  auto_route: ^9.2.2
  # shared_preferences: ^2.3.3  # TODO: Требует CocoaPods
  intl: ^0.19.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2
  # local_auth: ^2.3.0  # TODO: Требует CocoaPods
  flutter_animate: ^4.5.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  riverpod_generator: ^2.4.3
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/mock/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: PPObjectSans
      fonts:
        - asset: assets/fonts/PPObjectSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PPObjectSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PPObjectSans-Bold.ttf
          weight: 700
